"""Add receipt_id to transaction

Revision ID: 1a5659080071
Revises: 55fa097ed97e
Create Date: 2026-03-01 21:02:22.735671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5659080071'
down_revision: Union[str, None] = '55fa097ed97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receipt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'receipts', ['receipt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'receipt_id')
    # ### end Alembic commands ###
