"""add_household_invitations

Revision ID: 8231d14463cd
Revises: d5f32ad96784
Create Date: 2026-03-08 16:58:52.530902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8231d14463cd'
down_revision: Union[str, None] = 'd5f32ad96784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('owner', 'member', 'read_only', name='role', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_invitations_email'), 'household_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_household_invitations_household_id'), 'household_invitations', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_invitations_id'), 'household_invitations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_household_invitations_id'), table_name='household_invitations')
    op.drop_index(op.f('ix_household_invitations_household_id'), table_name='household_invitations')
    op.drop_index(op.f('ix_household_invitations_email'), table_name='household_invitations')
    op.drop_table('household_invitations')
    # ### end Alembic commands ###
