"""add suggested account to bank transactions

Revision ID: 89b2c595190e
Revises: 8231d14463cd
Create Date: 2026-03-09 21:12:10.792295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b2c595190e'
down_revision: Union[str, None] = '8231d14463cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('suggested_account_id', sa.Integer(), nullable=True))
    op.add_column('bank_transactions', sa.Column('suggested_account_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_transactions', 'suggested_account_name')
    op.drop_column('bank_transactions', 'suggested_account_id')
    # ### end Alembic commands ###
