"""add_file_hash_to_receipt

Revision ID: ab0aa2bcae25
Revises: d1c83dc4c36b
Create Date: 2026-03-22 16:14:47.195269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0aa2bcae25'
down_revision: Union[str, None] = 'd1c83dc4c36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_receipts_file_hash'), 'receipts', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_file_hash'), table_name='receipts')
    op.drop_column('receipts', 'file_hash')
    # ### end Alembic commands ###
