"""add auto_post to rules

Revision ID: d1c83dc4c36b
Revises: 89b2c595190e
Create Date: 2026-03-15 21:08:13.041489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c83dc4c36b'
down_revision: Union[str, None] = '89b2c595190e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column('rules', sa.Column('auto_post', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE rules SET auto_post = False")
    
    # Now make it NOT NULL
    op.alter_column('rules', 'auto_post', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'auto_post')
    # ### end Alembic commands ###
